config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  
  root to: 'homes#top'
  
  get 'home/about' => 'homes#about', as: 'about'
  
  resources :books
  
  resources :users, only: [:show, :edit, :index, :destroy, :update]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  def  self.search_for(search, word)
    if search == "perfect"
      @book = Book.where(title: word)
    elsif search == "forword"
      @book = Book.where("title LIKE?", "#{word}%")
    elsif search == "backword"
      @book = Book.where("title LIKE?", "%#{word}")
    elsif search == "partial"
      @book = Book.where("title LIKE?", "%#{word}%")
    else
      @book = Book.all
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence:true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :profile_image
  
  has_many :books, dependent: :destroy
  
  validates :name, length: { minimum: 2, maximum: 20}, uniqueness: true
  
  validates :introduction, length: { maximum: 50}
  
  def get_profile_image(width,height)
      
    unless profile_image.attached?
    
      file_path = Rails.root.join('app/assets/images.1/no_image.jpg')
    
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    
    end
    
      profile_image.variant(resize_to_limit: [width,height]).processed
  
  end
  
  GUEST_USER_EMAIL = "guest@example.com"
    
  def  self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
  
  def guest_user?
    email == GUEST_USER_EMAIL
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    before_action :authenticate_user!, except: [:top,:about]
    
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    def after_sign_in_path_for(resource)
      
      flash[:notice] = "Signed in successfully."

      user_path(current_user.id)
      
    end
    
    def after_sign_out_path_for(resource)
      
      flash[:notice] = "Signed out successfully."

       root_path

    end

  protected

  def configure_permitted_parameters
      
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :birth_date])
    
  end
    
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  def create
    @book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_params)
    comment.book_id = @book.id
    comment.save
    @book_comment = BookComment.new
    # redirect_to book_path(book)
  end

  def destroy
    @book = Book.find(params[:book_id])
    comment = BookComment.find(params[:id])
    comment.destroy
    @book_comment = BookComment.new
    # redirect_to book_path(book)
  end

  private
  
  def book_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    
    @books = Book.all
    
    @book_new = Book.new
    
    @user = current_user
    
    @book = Book.new
    
  end

  def show
    
    @book = Book.find(params[:id])
    
    @user = @book.user

    @book_new = Book.new

  end
  
  def create
    
    @book = Book.new(book_params)
    
    @book.user_id = current_user.id
    
    if @book.save
    
      flash[:notice] = "You have created book successfully."
    
      redirect_to book_path(@book.id)
    
    else
      
      @books = Book.all
    
      @book_new = Book.new
    
      @user = current_user
      
      render :index
    
    end
    
  end
  
  
  def edit
    
    is_matching_login_user
    
    @book = Book.find(params[:id])
    
  end
  
  def update
    
    is_matching_login_user
    
    @book = Book.find(params[:id])
    
    if @book.update(book_params)
    
    flash[:notice] = "You have updated book successfully."
    
    redirect_to book_path(@book.id)
    
    else
    
    
      
    render :edit
    
    end
    
  end
  
  def destroy
    
    book = Book.find(params[:id])
    
    book.destroy

    redirect_to '/books'
    
  end

  private

  def is_matching_login_user

    book = Book.find(params[:id])
    
    unless book.user_id == current_user.id
  
      redirect_to "/books"
  
    end
    
  end

  def book_params

    params.require(:book).permit(:title, :body)
  
  end
 
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new
    favorite.book_id = @book.id
    favorite.save
    # redirect_to request.referer
  end
  
  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    # redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    
    follow = current_user.active_relationships.build(follower_id: params[:user_id])
    follow.save
    redirect_to request.referer
    
  end

  def destroy
    follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    follow.destroy
    redirect_to request.referer
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    
  def search
    @range = params[:range]
    @search = params[:search]
    @word = params[:word]
    if @range == "User"
      @records = User.search_for(@search, @word)
    else
      @records = Book.search_for(@search, @word)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    
    @book = Book.new
    
    @user =User.find(params[:id])
    
    @books = @user.books
    
    @book_new = Book.new 
    
  end
  
  def cleate
  end
  
  def index
    
    @user = current_user
    
    @users = User.all
    
    @book_new = Book.new 
    
  end
  
  def edit
    
    is_matching_login_user
    
    @user = User.find(params[:id])
    
  end
  
  def update
    
    is_matching_login_user
    
    @user = User.find(params[:id])
    
    if @user.update(user_params)
    
      flash[:notice] = "You have updated user successfully."
    
      redirect_to user_path(@user.id)
    
    else
      
      render :edit
    
    end
  
  end

  private

  def  is_matching_login_user
  
    user = User.find(params[:id])
   
    unless user.id == current_user.id
    
      redirect_to user_path(current_user.id)
    
    end
    
  end

  def user_params
  
    params.require(:user).permit(:name, :introduction, :profile_image)
  
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/create.js.erb
$("#comment_area").html("<%= j(render 'books/comment', book: @book,book_comment: @book_comment) %>")
$("#counter_area").html("<%= j(render 'books/comment_counter', book: @book) %>")

app/views/book_comments/destroy.js.erb
$("#comment_area").html("<%= j(render 'books/comment', book: @book,book_comment: @book_comment) %>")
$("#counter_area").html("<%= j(render 'books/comment_counter', book: @book) %>")

app/views/books/_comment.html.erb
<table>
  <% book.book_comments.each do |book_comment| %>
    <tr>
      <td>
        <%= link_to (book_comment.user) do%>
          <%= image_tag book_comment.user.get_profile_image, size: "50x50" %><br>
          <%= book_comment.user.name %>
        <% end %>
      </td>
      <td><%= book_comment.comment %></td>
      <td>
        <% if current_user == book_comment.user %>
          <%= link_to "Destroy", book_book_comment_path(book, book_comment), method: :delete, remote: true, class: "btn btn-danger" %>
        <% end %> 
      </td>
    </tr>
  <% end %>
</table>
<%= form_with model: [book, book_comment], local: false do |f| %>
  <%= f.text_area :comment, style: "width:100%", rows: "3" %><br>
  <%= f.submit "送信" %>
<% end %>  

app/views/books/_comment_counter.html.erb
コメント数：<%= book.book_comments.count %> 

app/views/books/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    ♥<%= book.favorites.count %>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    ♡<%= book.favorites.count %>
  <% end %>
<% end %>

app/views/books/_form.html.erb
<%= form_with model: book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
        
        <td id= "favorite_buttons_<%= book.id %>">
          <%= render "/books/favorite", book: book %>
        </td>
        
        <td><%= render "books/comment_counter", book: book %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<%= render 'layouts/errors', obj: @book %>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td>
            <%= link_to(@book.user) do %>
              <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
              <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          
          <td id= "favorite_buttons_<%= @book.id %>">
            <%= render "/books/favorite", book: @book %>
          </td>
          
          <td id= "counter_area">
            <%= render "books/comment_counter", book: @book %>
          </td>
          <% if @book.user == current_user %> 
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
          <% end %>
        </tr>
      </table>
      
      <div id= "comment_area">
        <%= render "books/comment", book: @book, book_comment: @book_comment %>
      </div>
      
    </div>
  </div>
</div>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "books/favorite", book: @book) %>");

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "books/favorite", book: @book) %>");

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<%= flash[:notice] %>
<main>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong>!!</h1>
        <p>In  <i class="fa-solid fa-book"></i><strong>Bookers,</strong>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row mt-5">
            <%= link_to "ゲストログイン（閲覧用）", users_guest_sign_in_path, class: "btn btn-secondary btn-sm btn-block mb-3 sign_in", method: :post %>
          </div>
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>
</main>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/searches/search.html.erb
<% if @range == "User" %>
  <h3>Users search for "<%= @word %>"</h3>
  <%= render "users/index", users: @records %>
<% else %>
  <h3>Books search for "<%= @word %>"</h3>
  <%= render "books/index", books: @records %>
<% end %>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.active_relationships.count %></td>
        <td>フォロワー数：<%= user.passive_relationships.count %></td>
        <% unless current_user == user %>
          <% if user.followed_by?(current_user) %>
            <td><%= link_to "フォローを外す", user_relationships_path(user), method: :delete %></td>
          <% else %>
            <td><%= link_to "フォローする", user_relationships_path(user), method: :post %></td>
          <% end %>
        <% end %>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
	</tr>
	<tr>
	  <th>follows</th>
	  <th><%= link_to user.active_relationships.count, follows_user_path(user) %></th>
	</tr>
	<tr>
	  <th>followers</th>
	  <th><%= link_to user.passive_relationships.count, followers_user_path(user) %></th>
	</tr>
</table>
  <% unless current_user == user %>
    <% if user.followed_by?(current_user) %>
      <td><%= link_to "フォローを外す", user_relationships_path(user), method: :delete, class: "btn btn-info" %></td>
    <% else %>
      <td><%= link_to "フォローする", user_relationships_path(user), method: :post, class: "btn btn-success" %></td>
    <% end %>
  <% end %>


<div class='row'>
  <% if current_user == user %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model: @user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<h2>User followers</h2>
<% if @followers.empty? %>
  <%= "ユーザーはいません" %>
<% else %>
  <table class="table">
    <th>image</th>
    <th>name</th>
    <th colspan = "3"></th>
    <% @followers.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: "100x100" %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.active_relationships.count %></td>
        <td>フォロワー数：<%= user.passive_relationships.count %></td>
        <td><%= link_to "Show", user_path(user) %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/users/follows.html.erb
<h2>follow Users</h2>
<% if @follows.empty? %>
  <P><%= "ユーザーはいません" %></P>
<% else %>
  <table class= "table">
    <th>image</th>
    <th>name</th>
    <th colspan = "3"></th>
    <% @follows.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: "100x100" %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.active_relationships.count %></td>
        <td>フォロワー数：<%= user.passive_relationships.count %></td>
        <td><%= link_to "Show", user_path(user) %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
        <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>