config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  
  root to: 'homes#top'
  
  get 'home/about' => 'homes#about', as: 'about'
  
  resources :books
  
  resources :users, only: [:show, :edit, :index, :destroy, :update]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  def  self.search_for(search, word)
    if search == "perfect"
      @book = Book.where(title: word)
    elsif search == "forword"
      @book = Book.where("title LIKE?", "#{word}%")
    elsif search == "backword"
      @book = Book.where("title LIKE?", "%#{word}")
    elsif search == "partial"
      @book = Book.where("title LIKE?", "%#{word}%")
    else
      @book = Book.all
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence:true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :profile_image
  
  has_many :books, dependent: :destroy
  
  validates :name, length: { minimum: 2, maximum: 20}, uniqueness: true
  
  validates :introduction, length: { maximum: 50}
  
  def get_profile_image(width,height)
      
    unless profile_image.attached?
    
      file_path = Rails.root.join('app/assets/images.1/no_image.jpg')
    
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    
    end
    
      profile_image.variant(resize_to_limit: [width,height]).processed
  
  end
  
  GUEST_USER_EMAIL = "guest@example.com"
    
  def  self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
  
  def guest_user?
    email == GUEST_USER_EMAIL
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    before_action :authenticate_user!, except: [:top,:about]
    
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    def after_sign_in_path_for(resource)
      
      flash[:notice] = "Signed in successfully."

      user_path(current_user.id)
      
    end
    
    def after_sign_out_path_for(resource)
      
      flash[:notice] = "Signed out successfully."

       root_path

    end

  protected

  def configure_permitted_parameters
      
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :birth_date])
    
  end
    
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    
    @books = Book.all
    
    @book_new = Book.new
    
    @user = current_user
    
    @book = Book.new
    
  end

  def show
    
    @book = Book.find(params[:id])
    
    @user = @book.user

    @book_new = Book.new

  end
  
  def create
    
    @book = Book.new(book_params)
    
    @book.user_id = current_user.id
    
    if @book.save
    
      flash[:notice] = "You have created book successfully."
    
      redirect_to book_path(@book.id)
    
    else
      
      @books = Book.all
    
      @book_new = Book.new
    
      @user = current_user
      
      render :index
    
    end
    
  end
  
  
  def edit
    
    is_matching_login_user
    
    @book = Book.find(params[:id])
    
  end
  
  def update
    
    is_matching_login_user
    
    @book = Book.find(params[:id])
    
    if @book.update(book_params)
    
    flash[:notice] = "You have updated book successfully."
    
    redirect_to book_path(@book.id)
    
    else
    
    
      
    render :edit
    
    end
    
  end
  
  def destroy
    
    book = Book.find(params[:id])
    
    book.destroy

    redirect_to '/books'
    
  end

  private

  def is_matching_login_user

    book = Book.find(params[:id])
    
    unless book.user_id == current_user.id
  
      redirect_to "/books"
  
    end
    
  end

  def book_params

    params.require(:book).permit(:title, :body)
  
  end
 
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new
    favorite.book_id = @book.id
    favorite.save
    # redirect_to request.referer
  end
  
  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    # redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    
  def search
    @range = params[:range]
    @search = params[:search]
    @word = params[:word]
    if @range == "User"
      @records = User.search_for(@search, @word)
    else
      @records = Book.search_for(@search, @word)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    
    @book = Book.new
    
    @user =User.find(params[:id])
    
    @books = @user.books
    
    @book_new = Book.new 
    
  end
  
  def cleate
  end
  
  def index
    
    @user = current_user
    
    @users = User.all
    
    @book_new = Book.new 
    
  end
  
  def edit
    
    is_matching_login_user
    
    @user = User.find(params[:id])
    
  end
  
  def update
    
    is_matching_login_user
    
    @user = User.find(params[:id])
    
    if @user.update(user_params)
    
      flash[:notice] = "You have updated user successfully."
    
      redirect_to user_path(@user.id)
    
    else
      
      render :edit
    
    end
  
  end

  private

  def  is_matching_login_user
  
    user = User.find(params[:id])
   
    unless user.id == current_user.id
    
      redirect_to user_path(current_user.id)
    
    end
    
  end

  def user_params
  
    params.require(:user).permit(:name, :introduction, :profile_image)
  
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <a class="navbar-brand" href="/"><span>Bookers</span></a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">

      <span class="navbar-toggler-icon"></span>

    </button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      
      <ul class="navbar-nav ml-auto">
        
        <% if user_signed_in? %>
      
          <li class= "nav-link text-light">
          <%= link_to(user_path(current_user.id), class: "text-light") do %>
          <strong><i class="fa-solid fa-home"></i><span>Home</span></strong>
          <% end %>
          </li>
    
          <li class= "nav-link text-light">
          <%= link_to(users_path, class: "text-light") do %>
          <strong><i class="fa-solid fa-users"></i><span>Users</span></strong>
          <% end %>
          </li>
  
          <li class= "nav-link text-light">
          <%= link_to(books_path, class: "text-light") do %>
          <strong><i class="fa-solid fa-book-open"></i><span>Books</span></strong>
          <% end %>
          </li>
          
          <li class= "nav-link text-light">
          <%= link_to(destroy_user_session_path, method: :delete, class: "text-light") do %>
          <strong><i class="fa-solid fa-sign-out-alt"></i><span>Log out</span></strong>
          <% end %>
          </li>
    
        <% else %>
    
      <li class= "nav-link text-light">
      <%= link_to(root_path, class: "text-light") do %>
      <strong><i class="fa-solid fa-home"></i><span>Home</span></strong>
      <% end %>
      </li>
    
      <li class= "nav-link text-light">
      <%= link_to(about_path, class: "text-light") do %>
      <strong><i class="fa-solid fa-link"></i><span>About</span></strong>
      <% end %>
      </li>
      
      <li class= "nav-link text-light">
      <%= link_to(new_user_registration_path, class: "text-light") do %>
       <strong><i class="fa-solid fa-user-plus"></i><span>Sign up</span></strong>
      <% end %>
      </li>
      
      <li class= "nav-link text-light">
      <%= link_to(new_user_session_path, class: "text-light") do %>
       <strong><i class="fa-solid fa-sign-in-alt"></i><span>Log in</span></strong>
      <% end %>
      </li>
  
  <% end %>
    
</ul>
     

        

</header>

app/views/layouts/_search.html.erb
<% if user_signed_in? %>
  <div class= "search_form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([["User"], ["Book"]]) %>
      <%= f.select :search, options_for_select([["完全一致", "perfect"], ["前方一致","forword"], ["後方一致", "backword"], ["部分一致","partial"]]) %>
      <%= f.submit "検索" %>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Ver2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
   <script src="https://kit.fontawesome.com/95b647ef78.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <main>
        <p id="notice"><%= notice %></p>
        <%= yield %>
      </main>
    <%= render 'layouts/footer' %>
  </body>
</html>